export const initCustomerData = {
    email: "",
    brand: "",
    password: "",
    name: "",
    surname: "",
    countryCode: "",
    country: { name: '', code3: '' },
    address: "",
    addressTwo: "",
    province: "",
    city: "",
    status: 1,
    telegram: "",
    synapsSessionId: "",
    solanaAddress: "",
    wallets: [{ account: '', chainId: 0 }],
    changePasswordNextLogin: true,
}

// When creating a new object, include properties that have truthy values in the original object.
export const mappingEditableData = {
    createdAt: false,
    internal: false,
    primaryWallet: false,
    updatedAt: false,
    __v: false,
    _id: false,
    email: true,
    brand: true,
    password: true,
    name: true,
    surname: true,
    countryCode: true,
    country: true,
    address: true,
    addressTwo: true,
    province: true,
    city: true,
    status: true,
    telegram: true,
    synapsSessionId: true,
    solanaAddress: true,
    wallets: true,
    changePasswordNextLogin: true,
};